### PR TITLE
ARC-1370: Content-Negotiation for eHealth Relying Party

### PR DESCRIPTION
**Pull request by thomasrichner-oviva**
- pull out authentication endpoint business logic into a service
- enable content-negotiation on some endpoints for flexible usage

### CODE REVIEW

**Comment by thomasrichner-oviva** [comment]
@eduardOrthopy please have a look and let me know whether this suits your needs. Did some refactoring of my crimes in the past.

**Comment by eduardOrthopy** [comment]
@thomasrichner-oviva thanks a lot for putting in all that work. I will check it out as soon as I can.

**Comment by thomasrichner-oviva** [comment]
@eduardOrthopy  re-opened a refactored version here: https://github.com/oviva-ag/ehealthid-relying-party/pull/44

**Comment by eduardOrthopy** [comment]
@thomasrichner-oviva nice. I will check and transfer my comments to over there.

#44 is a lot smaller/slimmer. Very nice ❤️

**Comment by thomasrichner-oviva** [comment]
closing in favour of #44

**Pull request closed without merging**
